### PR TITLE
Added `<?=` and `<.=`.

### PR DESCRIPTION
**Pull request by minad**

### CODE REVIEW

**Comment by neongreen** [comment]
Thanks for writing descriptions as well! Merged.

**Comment by neongreen** [comment]
(And sorry for a long wait – I had a flight to Spain yesterday and was too tired to merge anything :)

Released as microlens-mtl-0.1.10.

**Comment by minad** [comment]
Hi, thx for merging. I found another one to be missing: (<?~) Probably there are still more missing. Maybe we can just grep over the microlens and lens codebase and see ;)

**Comment by minad** [comment]
~~~ shell
ops() { find $1 -name '*.hs' | xargs grep -hoPr '\([^\w\(\)]+\)' | sort | uniq }; diff <(ops microlens) <(ops lens) | grep -P '^[<>]' | sort
~~~

~~~
< ('<$>')
< ('!!')
< ('$!')
< (@+=@)
> (^^~)
> (^^=)
> (^~)
> (^=)
> (^@?!)
> (^@?)
> (^@..)
> (^@.)
> (^#)
> (<^^~)
> (<^^=)
> (<^~)
> (<^=)
> (<<^^~)
> (<<^^=)
> (<<^~)
> (<<^=)
> (<<~)
> (<<<>~)
> (<<<>=)
> (<<</>~)
> (<<</>=)
> (<<<.>~)
> (<<<.>=)
> (<<>~)
> (<<>=)
> (<<||~)
> (<<||=)
> (<<-~)
> (<<-=)
> (<</>~)
> (<</>=)
> (<<//~)
> (<<//=)
> (<<.>~)
> (<<.>=)
> (<<.|.~)
> (<<.|.=)
> (<<.&.~)
> (<<.&.=)
> (<<*~)
> (<<*=)
> (<<**~)
> (<<**=)
> (<<&&~)
> (<<&&=)
> (<<%@~)
> (<<%@=)
> (<<+~)
> (<<+=)
> (<>~)
> (<>=)
> (<>)
> (<|>)
> (<||~)
> (<||=)
> (<|)
> (<-~)
> (<-=)
> (<!>)
> (<?~)
> (</>~)
> (</>=)
> (</>)
> (<//~)
> (<//=)
> (<.~)
> (<.>~)
> (<.>=)
> (<.>)
> (<.|.~)
> (<.|.=)
> (<.)
> (<.&.~)
> (<.&.=)
> (<@>)
> (<@)
> (<$>)
> (<$)
> (<*~)
> (<*=)
> (<*)
> (<**~)
> (<**=)
> (<&&~)
> (<&&=)
> (<#~)
> (<#=)
> (<#%~)
> (<#%=)
> (<%@~)
> (<%@=)
> (<+~)
> (<+=)
> (=='|')
> (=='@')
> (==)
> (>>>)
> (>>-)
> (|>)
> (||~)
> (||=)
> (|||)
> (|*)
> ( #~ )
> ( #= )
> ( # )
> ( #%~ )
> ( #%= )
> ( #%%~ )
> ( #%%= )
> (-~)
> (,,,,,,,,)
> (,,,,,,,)
> (,,,,,,)
> (,,,,,)
> (:<)
> (:>)
> (:@)
> (:*:)
> (!)
> (??)
> (/=)
> (//~)
> (.>)
> (.|.~)
> (.|.=)
> (...)
> (.@~)
> (.@=)
> (.&.~)
> (.&.=)
> (.&.)
> ('^^~')
> ('^^=')
> ('^~')
> ('^=')
> ('^@?!')
> ('^@?')
> ('^@..')
> ('^@.')
> ('^#')
> ('<^^~')
> ('<^^=')
> ('<^~')
> ('<^=')
> ('<<^^~')
> ('<<^^=')
> ('<<^~')
> ('<<^=')
> ('<<~')
> ('<<<>~')
> ('<<<>=')
> ('<<||~')
> ('<<||=')
> ('<<-~')
> ('<<-=')
> ('<<//~')
> ('<<//=')
> ('<<*~')
> ('<<*=')
> ('<<**~')
> ('<<**=')
> ('<<&&~')
> ('<<&&=')
> ('<<%@~')
> ('<<%@=')
> ('<<+~')
> ('<<+=')
> ('<>~')
> ('<>=')
> ('<||~')
> ('<||=')
> ('<-~')
> ('<-=')
> ('<?~')
> ('</>~')
> ('</>=')
> ('<//~')
> ('<//=')
> ('<.~')
> ('<.>~')
> ('<.>=')
> ('<.|.~')
> ('<.|.=')
> ('<.&.~')
> ('<.&.=')
> ('<$')
> ('<*~')
> ('<*=')
> ('<*>')
> ('<**~')
> ('<**=')
> ('<&&~')
> ('<&&=')
> ('<%@~')
> ('<%@=')
> ('<+~')
> ('<+=')
> ('||~')
> ('||=')
> ('-~')
> ('??')
> ('//~')
> ('.|.~')
> ('.|.=')
> ('.@~')
> ('.@=')
> ('.&.~')
> ('.&.=')
> ('$')
> ('*~')
> ('**~')
> ('**=')
> ('\'':)
> ('&&~')
> ('&&=')
> ('#')
> ('%@~')
> ('%@=')
> ('%%~')
> ('%%=')
> ('%%@~')
> ('%%@=')
> ('+~')
> ("!!!","!!!")
> (@>)
> (@|>@)
> ($!)
> (*~)
> (*>)
> (* -> * -> * -> * -> * -> *)
> (*)
> (**~)
> (**=)
> (***)
> (&~)
> (&&~)
> (&&=)
> (&&&)
> (#)
> (%@~)
> (%@=)
> (%%~)
> (%%@~)
> (%%@=)
> (+~)
> (+)
> (++)
> (+++)
~~~

**Comment by neongreen** [comment]
Are you adding them just for completeness? I should've asked before merging
:)

Completeness/consistency are worthy goals, but for microlens different
goals take priority (namely, I try to keep compilation times small, I don't
include operators that are very rarely used even if it would make sense to
include them from the viewpoint of consistency, and I give priority to
functions that actual users requests or functions that are hard to
implement without much knowledge of lens).

On 4 Aug 2016 5:27 p.m., "Daniel Mendler" <notifications@github.com> wrote:

ops() { find $1 -name '*.hs' | xargs grep -hoPr '\([^\w\(\)]+\)' |
sort | uniq }; diff <(ops microlens) <(ops lens) | grep -P '^[<>]' |
sort

< ('<$>')
< ('!!')
< ('$!')
< (@+=@)
> (^^~)
> (^^=)
> (^~)
> (^=)
> (^@?!)
> (^@?)
> (^@..)
> (^@.)
> (^#)
> (<^^~)
> (<^^=)
> (<^~)
> (<^=)
> (<<^^~)
> (<<^^=)
> (<<^~)
> (<<^=)
> (<<~)
> (<<<>~)
> (<<<>=)
> (<<</>~)
> (<<</>=)
> (<<<.>~)
> (<<<.>=)
> (<<>~)
> (<<>=)
> (<<||~)
> (<<||=)
> (<<-~)
> (<<-=)
> (<</>~)
> (<</>=)
> (<<//~)
> (<<//=)
> (<<.>~)
> (<<.>=)
> (<<.|.~)
> (<<.|.=)
> (<<.&.~)
> (<<.&.=)
> (<<*~)
> (<<*=)
> (<<**~)
> (<<**=)
> (<<&&~)
> (<<&&=)
> (<<%@~)
> (<<%@=)
> (<<+~)
> (<<+=)
> (<>~)
> (<>=)
> (<>)
> (<|>)
> (<||~)
> (<||=)
> (<|)
> (<-~)
> (<-=)
> (<!>)
> (<?~)
> (</>~)
> (</>=)
> (</>)
> (<//~)
> (<//=)
> (<.~)
> (<.>~)
> (<.>=)
> (<.>)
> (<.|.~)
> (<.|.=)
> (<.)
> (<.&.~)
> (<.&.=)
> (<@>)
> (<@)
> (<$>)
> (<$)
> (<*~)
> (<*=)
> (<*)
> (<**~)
> (<**=)
> (<&&~)
> (<&&=)
> (<#~)
> (<#=)
> (<#%~)
> (<#%=)
> (<%@~)
> (<%@=)
> (<+~)
> (<+=)
> (=='|')
> (=='@')
> (==)
> (>>>)
> (>>-)
> (|>)
> (||~)
> (||=)
> (|||)
> (|*)
> ( #~ )
> ( #= )
> ( # )
> ( #%~ )
> ( #%= )
> ( #%%~ )
> ( #%%= )
> (-~)
> (,,,,,,,,)
> (,,,,,,,)
> (,,,,,,)
> (,,,,,)
> (:<)
> (:>)
> (:@)
> (:*:)
> (!)
> (??)
> (/=)
> (//~)
> (.>)
> (.|.~)
> (.|.=)
> (...)
> (.@~)
> (.@=)
> (.&.~)
> (.&.=)
> (.&.)
> ('^^~')
> ('^^=')
> ('^~')
> ('^=')
> ('^@?!')
> ('^@?')
> ('^@..')
> ('^@.')
> ('^#')
> ('<^^~')
> ('<^^=')
> ('<^~')
> ('<^=')
> ('<<^^~')
> ('<<^^=')
> ('<<^~')
> ('<<^=')
> ('<<~')
> ('<<<>~')
> ('<<<>=')
> ('<<||~')
> ('<<||=')
> ('<<-~')
> ('<<-=')
> ('<<//~')
> ('<<//=')
> ('<<*~')
> ('<<*=')
> ('<<**~')
> ('<<**=')
> ('<<&&~')
> ('<<&&=')
> ('<<%@~')
> ('<<%@=')
> ('<<+~')
> ('<<+=')
> ('<>~')
> ('<>=')
> ('<||~')
> ('<||=')
> ('<-~')
> ('<-=')
> ('<?~')
> ('</>~')
> ('</>=')
> ('<//~')
> ('<//=')
> ('<.~')
> ('<.>~')
> ('<.>=')
> ('<.|.~')
> ('<.|.=')
> ('<.&.~')
> ('<.&.=')
> ('<$')
> ('<*~')
> ('<*=')
> ('<*>')
> ('<**~')
> ('<**=')
> ('<&&~')
> ('<&&=')
> ('<%@~')
> ('<%@=')
> ('<+~')
> ('<+=')
> ('||~')
> ('||=')
> ('-~')
> ('??')
> ('//~')
> ('.|.~')
> ('.|.=')
> ('.@~')
> ('.@=')
> ('.&.~')
> ('.&.=')
> ('$')
> ('*~')
> ('**~')
> ('**=')
> ('\'':)
> ('&&~')
> ('&&=')
> ('#')
> ('%@~')
> ('%@=')
> ('%%~')
> ('%%=')
> ('%%@~')
> ('%%@=')
> ('+~')
> ("!!!","!!!")
> (@>)
> (@|>@)
> ($!)
> (*~)
> (*>)
> (* -> * -> * -> * -> * -> *)
> (*)
> (**~)
> (**=)
> (***)
> (&~)
> (&&~)
> (&&=)
> (&&&)
> (#)
> (%@~)
> (%@=)
> (%%~)
> (%%@~)
> (%%@=)
> (+~)
> (+)
> (++)
> (+++)

—
You are receiving this because you modified the open/close state.

Reply to this email directly, view it on GitHub
<https://github.com/aelve/microlens/pull/82#issuecomment-237588781>, or mute
the thread

**Comment by minad** [comment]
No, no. I needed them. So I am using now the microlens exported versions ;)

For the future, I just thought that it wouldn't be a problem to add even more operators and function which wouldn't introduce additional dependencies. I don't know how much each of those operators will add to the compilation time. For me the issue is the seemingly huge dependency graph of lens.

**Comment by neongreen** [comment]
It's not that they will add much compilation time, it's that they will decrease the total amount of combinators I'm able to add before I run out of compilation time budget – which is why currently I'm operating on the “add things when people request them” basis (with the exception of several first versions, when there were no users yet and I was just adding things I thought people would need).

> For me the issue is the seemingly huge dependency graph of lens.

I have a somewhat stricter goal for microlens – not only it should have few dependencies, but it should be tiny enough to make -using it- a decision without any drawbacks. It's hard to use lens as a utility library when you're a library writer and not an application writer, so microlens tries to be such an utility library instead (among other things). So, having very fast compilation helps; not having tons of operators helps as well.

**Pull request merged**
