### PR TITLE
Consider exposing Lens.Micro.Mtl.Zoom

### PR DESCRIPTION
**Pull request by kustosz**
Hi,
I'm currently using my own instances of `Zoom` and `Zoomed` for some custom monads I use and this is the last thing making me stick to `lens`. Having `Lens.Micro.Mtl.Zoom` available would really come in handy (and finally made it possible to use `mircrolens`). Can we do this? :)

Cheers,
Marcin Kostrzewa

### CODE REVIEW

**Comment by neongreen** [comment]
Okay, sure. Let's do it a bit differently, tho. I propose the following plan:

* rename `Lens.Micro.Mtl.Zoom` to `Lens.Micro.Mtl.Internal`
* move `Zoom` and `Magnify` to `Lens.Micro.Mtl.Internal`
* make `Lens.Micro.Mtl.Internal` available

Can you do it? (If you'd rather not, just say and I'll do it myself.)

**Comment by kustosz** [comment]
Done :)

**Comment by neongreen** [comment]
Okay, I'll look at it and merge it later today / tomorrow. If I forget, please ping me!

**Comment by neongreen** [comment]
@kustosz, I have released microlens-mtl-0.1.6 that incorporates this change.

Thanks!

**Comment by kustosz** [comment]
Great, thank you!

**Pull request merged**
