### PR TITLE
Export &~ from microlens-mtl

### PR DESCRIPTION
**Pull request by dbaynard**
Add a function to use the `MonadState` machinery more easily.

The code is right out of `Control.Lens.Lens`. No extra imports, etc.

### CODE REVIEW

**Comment by neongreen** [comment]
Okay, will merge and release tomorrow.

**Comment by dbaynard** [comment]
Great. Thanks (though don't rush a release on my part). Happy merging!

**Comment by neongreen** [comment]
> though don't rush a release on my part

Great, then I won't :) Releases are a pain in the ass.

**Comment by dbaynard** [comment]
@neongreen Actually, I have some more suggestions of combinators to add: `<>=`, `<~` and possibly some more. Again, no need to rush a release — but if you were planning one, would you be willing to holding off?

**Comment by neongreen** [comment]
@dbaynard I'm not sure where your message about operators has gone:

> I have some more suggestions of combinators to add: <>=, <~ and possibly some more.

Anyway, I don't object to operators but only if you actually needed them at some point when using microlens.

**Comment by dbaynard** [comment]
Sorry, I deleted because `<~` is already there (I just didn't notice it) and the docs said you didn't want to implement `<>=`.

I'll bear your recent message in mind, then. Thanks!

**Comment by neongreen** [comment]
Released in microlens-mtl-0.1.11.

**Pull request merged**
